### ISSUE TITLE
when you divide two integers like 9 / 5, the result is also an integer, which means it will truncate the decimal part, resulting in the value 1.  To fix this issue and perform accurate temperature conversion, you should use floating-point numbers in your division operation

### ISSUE THREAD

**Issue by tallinn-learning** [LohurLaura/homework03#2]
https://github.com/LohurLaura/homework03/blob/a0b89783a4d038100ddc607ef7dace2e191cc55e/src/Main.java#L18C10-L18C10

like this:

double c = 26;    // Variable (c) means temperature in Celsius
double f = (9.0 / 5.0) * c + 32;
System.out.println(f);

**Comment by LohurLaura** [comment]
Corrected the code, thank you.
