### ISSUE TITLE
example

### ISSUE THREAD

**Issue by tallinn-learning** [LohurLaura/homework03#3]
https://github.com/LohurLaura/homework03/blob/a0b89783a4d038100ddc607ef7dace2e191cc55e/src/Main.java#L21

        char originalChar = 'A'; // Replace with the character you want to encrypt
        int shiftAmount = 3;   // Replace with the number of positions to shift

        // Encrypt the character by adding the shift amount to its Unicode value
        char encryptedChar = (char) (originalChar + shiftAmount);

        // Display the original character and the modified character
        System.out.println("Original Character: " + originalChar);
        System.out.println("Encrypted Character: " + encryptedChar);

**Comment by LohurLaura** [comment]
Corrected the code, thank you.
